### ISSUE TITLE
Failing specs on Supermarket Cookbook in Omnibus Install

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1056]
There are two failing specs in the omnibus-supermarket cookbook.

To reproduce:
```bash
  $ cd omnibus-supermarket
  $ cd cookbooks/omnibus-supermarket
  $ bundle
  $ bundle exec rspec
```
Which will output
```bash
Failures:

  1) omnibus-supermarket::database creates /var/opt/supermarket/etc/database.yml
     Failure/Error: end.converge(described_recipe)
     ChefSpec::Error::CommandNotStubbed:
       Executing a real command is disabled. Unregistered command:

           command("echo '\\dx' | psql supermarket | grep plpgsql")

       You can stub this command with:

           stub_command("echo '\\dx' | psql supermarket | grep plpgsql").and_return(...)
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.1.1/lib/chefspec/extensions/chef/conditional.rb:9:in `evaluate_command'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource/conditional.rb:75:in `evaluate'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource/conditional.rb:68:in `continue?'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:713:in `block in should_skip?'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:712:in `each'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:712:in `find'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:712:in `should_skip?'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.1.1/lib/chefspec/extensions/chef/resource.rb:19:in `run_action'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:49:in `run_action'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block (2 levels) in converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:81:in `each'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block in converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection.rb:96:in `execute_each_resource'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:80:in `converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/client.rb:345:in `converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.1.1/lib/chefspec/solo_runner.rb:124:in `converge'
     # ./spec/recipes/database_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/recipes/database_spec.rb:9:in `block (2 levels) in <top (required)>'

  2) omnibus-supermarket::database symlinks database.yml
     Failure/Error: end.converge(described_recipe)
     ChefSpec::Error::CommandNotStubbed:
       Executing a real command is disabled. Unregistered command:

           command("echo '\\dx' | psql supermarket | grep plpgsql")

       You can stub this command with:

           stub_command("echo '\\dx' | psql supermarket | grep plpgsql").and_return(...)
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.1.1/lib/chefspec/extensions/chef/conditional.rb:9:in `evaluate_command'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource/conditional.rb:75:in `evaluate'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource/conditional.rb:68:in `continue?'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:713:in `block in should_skip?'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:712:in `each'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:712:in `find'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource.rb:712:in `should_skip?'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.1.1/lib/chefspec/extensions/chef/resource.rb:19:in `run_action'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:49:in `run_action'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block (2 levels) in converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:81:in `each'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block in converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/resource_collection.rb:96:in `execute_each_resource'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/runner.rb:80:in `converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chef-11.16.4/lib/chef/client.rb:345:in `converge'
     # /Users/nshamrell/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.1.1/lib/chefspec/solo_runner.rb:124:in `converge'
     # ./spec/recipes/database_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/recipes/database_spec.rb:19:in `block (2 levels) in <top (required)>'

Finished in 13.54 seconds (files took 2.12 seconds to load)
32 examples, 2 failures

Failed examples:

rspec ./spec/recipes/database_spec.rb:8 # omnibus-supermarket::database creates /var/opt/supermarket/etc/database.yml
rspec ./spec/recipes/database_spec.rb:18 # omnibus-supermarket::database symlinks database.yml
```

**Comment by nellshamrell** [comment]
Fixed in https://github.com/chef/omnibus-supermarket/pull/43
