### ISSUE TITLE
Broken response from https://supermarket.chef.io/universe 

### ISSUE THREAD

**Issue by philicious** [chef/supermarket#1137]
as of today, we are seeing most calls to https://supermarket.chef.io/universe via Berkshelf being broken/truncated in the middle of the JSON response. 

(berkshelf-api-client-1.3.0 doesnt seem to detect this and doing auto-retries as wget does)

replicated with wget
```
wget https://supermarket.chef.io/universe
--2015-10-02 14:20:15--  https://supermarket.chef.io/universe
Resolving supermarket.chef.io (supermarket.chef.io)... 54.148.167.233, 54.213.34.209
Connecting to supermarket.chef.io (supermarket.chef.io)|54.148.167.233|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘universe.12’
[<=>                                        ] 72,882      88.9KB/s   in 0.8s
2015-10-02 14:20:17 (88.9 KB/s) - Read error at byte 72882 (Success).Retrying.
```

this was also confirmed by someone else in IRC

Finally this leads to JSON parser errors
```
0.15.12":{"location_type":"opscode","location_path":"https://supermarket.chef' (JSON::ParserError)
	from /var/lib/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /data/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/middleware/parse_json.rb:30:in `parse'
	from /data/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/middleware/parse_json.rb:100:in `on_complete'
	from /var/lib/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /var/lib/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /var/lib/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /var/lib/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /var/lib/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:376:in `run_request'
	from /var/lib/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /data/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-api-client-1.3.0/lib/berkshelf/api_client/connection.rb:62:in `universe'
	from /data/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/source.rb:22:in `build_universe'
	from /data/jenkins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/installer.rb:21:in `block (2 levels) in build_universe'
```

**Comment by conorbranagan** [comment]
:+1: We're experiencing this as well

**Comment by philicious** [comment]
seems to be resolved, see http://status.chef.io/
