### ISSUE TITLE
Authentication fails for new users

### ISSUE THREAD

**Issue by surfi2000** [chef/supermarket#1238]
When using LDAP backed authentication and a new user tries to log in to supermarket the following error is thrown:

`2016-02-26_21:46:45.14846 I, [2016-02-26T13:46:45.148281 #34565]  INFO -- : Started POST "/id/auth/chef/callback" for 192.168.63.3 at 2016-02-26 13:46:45 -0800
2016-02-26_21:46:45.15100 I, [2016-02-26T13:46:45.150949 #34565]  INFO -- : (chef) Callback phase initiated.
2016-02-26_21:46:45.22384 I, [2016-02-26T13:46:45.223774 #34565]  INFO -- : Processing by SessionsController#create as HTML
2016-02-26_21:46:45.22396 I, [2016-02-26T13:46:45.223910 #34565]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "username"=>"test_user", "password"=>"[FILTERED]", "commit"=>"Sign In"}
2016-02-26_21:46:45.25411 I, [2016-02-26T13:46:45.254022 #34565]  INFO -- : Completed 500 Internal Server Error in 30ms
2016-02-26_21:46:45.30231 F, [2016-02-26T13:46:45.302215 #34565] FATAL -- :
2016-02-26_21:46:45.30234 NoMethodError (undefined method `username' for nil:NilClass):
2016-02-26_21:46:45.30235   app/helpers/sessions_helper.rb:12:in `sign_in'
2016-02-26_21:46:45.30235   app/controllers/sessions_controller.rb:9:in `create'
2016-02-26_21:46:45.30235
2016-02-26_21:46:45.30236`

Steps to reproduce

1. Set up a new Chef server that uses a company LDAP server for authentication.
2. Set up Supermarket and link it to use the above Chef server.
3. Attempt to log into supermarket with an account that has never authenticated to the Chef server

Expected behaviour

I would expect that the user is shown the usual 'first time login' UI asking the user if they want to merge their chef account or create a new one

**Comment by nellshamrell** [comment]
Unfortunately, as Supermarket is build right now, each user MUST log into their Chef Server account and authorize Supermarket to use the credentials from their personal Chef Server account.  There is no current way to skip this step for each user.  We can consider this as a feature, but it will need to go through our normal work planning and prioritization process.

**Comment by surfi2000** [comment]
I understand the need for this, however, it's currently not being handled correctly. In the scenario above the user is presented with a plain error page without any guidance on why an internal server error is shown on screen. The scenario should be handled by the app and present a meaningful message to the user or redirect to the 'create account' page of the chef server.
