### ISSUE TITLE
Rails console errors in omnibus package

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1271]
After bringing in the omnibus packaging, the Supermarket rails console throws an error:

```
$ sudo env PATH=/opt/supermarket/embedded/bin bin/rails console production
/opt/supermarket/embedded/lib/ruby/2.1.0/irb/completion.rb:9:in `require': cannot load such file -- readline (LoadError)
    from /opt/supermarket/embedded/lib/ruby/2.1.0/irb/completion.rb:9:in `<top (required)>'
```

**Comment by robbkidd** [comment]
First suspect, [the upgrade of omnibus-software](https://github.com/chef/supermarket/pull/1255/commits/d2470f47e681f7384f6c468432a7c0554d5e8997) included in the unification. A change to the Ruby software definition within that commit range [omits `readline` from the Ruby compilation](https://github.com/chef/omnibus-software/compare/630a1484313540127ad37b91bc9c157f377bc665...e8124b356fed937a6e646cdd194f9eaa06f325e6#diff-b7915a1c384a6ad708ed53c14a27ab10R170).
