### ISSUE TITLE
Failing Javascript Spec

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1432]
At some point our Javascript spec started failing.
```
INFO [karma]: Karma v0.10.10 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
ERROR [karma]: [TypeError: Cannot read property 'charAt' of null]
TypeError: Cannot read property 'charAt' of null
  at Object.posix.isAbsolute (path.js:462:14)
  at Object.posix.normalize (path.js:444:26)
  at Object._getCommand (/Users/nshamrell/Projects/supermarket/src/supermarket/node_modules/karma/lib/launchers/Base.js:106:20)
  at Object._start (/Users/nshamrell/Projects/supermarket/src/supermarket/node_modules/karma-phantomjs-launcher/index.js:53:28)
  at Object.start (/Users/nshamrell/Projects/supermarket/src/supermarket/node_modules/karma/lib/launchers/Base.js:36:10)
  at /Users/nshamrell/Projects/supermarket/src/supermarket/node_modules/karma/lib/launcher.js:38:15
  at Array.forEach (native)
  at [object Object].launch (/Users/nshamrell/Projects/supermarket/src/supermarket/node_modules/karma/lib/launcher.js:12:11)
  at [object Object].invoke (/Users/nshamrell/Projects/supermarket/src/supermarket/node_modules/karma/node_modules/di/lib/injector.js:75:15)
  at Server.<anonymous> (/Users/nshamrell/Projects/supermarket/src/supermarket/node_modules/karma/lib/server.js:54:16)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:129:20)
  at net.js:1144:12
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

rake aborted!

/Users/nshamrell/Projects/supermarket/src/supermarket/lib/tasks/spec/javascripts.rake:9:in `block (3 levels) in <top (required)>'
/opt/chefdk/embedded/bin/bundle:22:in `load'
/opt/chefdk/embedded/bin/bundle:22:in `<main>'
Tasks: TOP => spec:all => spec:javascripts => spec:javascripts:run
(See full trace by running task with --trace)
```

**Comment by nellshamrell** [comment]
We need to remove this spec.
