### ISSUE TITLE
Error on db:seed in production

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1446]
```
(ec2_url)      ---- Begin output of bundle exec rake db:migrate db:seed ----
(ec2_url)        STDOUT: I, [2016-10-10T17:21:22.465555 #5181]  INFO -- : ** [Raven] Raven 0.13.3 ready to catch errors
(ec2_url)        == 20160914215547 MoveQualityMetricResults: migrating =========================
(ec2_url)        == 20160914215547 MoveQualityMetricResults: migrated (27.1922s) ===============
(ec2_url)        STDERR: I, [2016-10-10T17:21:19.951477 #5181]  INFO -- : Celluloid 0.17.4 is running in BACKPORTED mode. [ http://gi
t.io/vJf3J ]
(ec2_url)        Auto-loading of `.env.production` will be removed in 1.0. See https://github.com/bkeepers/dotenv-deployment if you w
ould like to continue using this feature.
(ec2_url)        rake aborted!
(ec2_url)        StandardError: An error has occurred, this and all later migrations canceled:
(ec2_url)  
(ec2_url)       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "unique_schema_migrations"
(ec2_url)       DETAIL:  Key (version)=(20160914215547) already exists.
ec2-52-10-243-72.us-west-2.compute.amazonaws.com      : INSERT INTO "schema_migrations" ("version") VALUES ($1)/opt/supermarket/embedded/service/supermarket/vendor/bundle
/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
(ec2_url)        /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/c
onnection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
(ec2_url)       /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/c
onnection_adapters/abstract_adapter.rb:484:in `block in log'
```

**Comment by robbkidd** [comment]
Keeping an eye on this one during our next post-2.8.34 release (because we've got a migration pending).

**Comment by nellshamrell** [comment]
Haven't seen this repeated, going ahead and closing.
