### ISSUE TITLE
Can't use stove to upload cookbooks to private supermarket

### ISSUE THREAD

**Issue by Poohblah** [chef/supermarket#1630]
I'm investigating adding [stove](http://sethvargo.github.io/stove/) and a private Supermarket to my team's Chef workflow.  I stood up Supermarket in an RHEL 7 testkitchen instance using the `supermarket-omnibus-cookbook` cookbook and had no trouble uploading cookbooks using `knife cookbook site upload`.  However, Supermarket throws a 500 error when uploading cookbooks using stove:

```
> ~/.chefdk/gem/ruby/2.3.0/bin/stove --endpoint https://testkitchen-cub-rh7.colorado.edu --no-ssl-verify --log-level debug --no-git
                      Stove::Cli | ===> Options: {:endpoint=>"https://testkitchen-cub-rh7.colorado.edu", :username=>"hendrenj", :key=>"/home/jay/.chef/user.pem", :extended_metadata=>true, :ssl_verify=>false, :remote=>"origin", :branch=>"master", :sign=>false, :artifactory=>false, :artifactory_key=>nil, :log_level=>"debug", :path=>"/home/jay/Work/git/cookbooks/cub_policy_common", :no_git=>true}
                      Stove::Cli | ===> ARGV: []
                   Stove::Runner | ===> Skipping plugin `:git'
                   Stove::Runner | ===> Running plugin `:community'
                Stove::Validator | ===> Running validations for `community.username'
                Stove::Validator |      Validation username passed!
                Stove::Validator | ===> Running validations for `community.key'
                Stove::Validator |      Validation key passed!
        Stove::Plugin::Community | ===> Publishing the release to the Chef community site
             ChefAPI::Connection | ===> POST cookbooks...
             ChefAPI::Connection |      Chef flavor: :open_source
             ChefAPI::Connection | ===> Building URI...
             ChefAPI::Connection |      Detected URI is relative
             ChefAPI::Connection |      Appending cookbooks to https://testkitchen-cub-rh7.colorado.edu
             ChefAPI::Connection | ===> Adding request headers...
             ChefAPI::Connection |      Accept: application/json
             ChefAPI::Connection |      Content-Type: application/json
             ChefAPI::Connection |      Connection: keep-alive
             ChefAPI::Connection |      Keep-Alive: 30
             ChefAPI::Connection |      User-Agent: ChefAPI Ruby Gem 0.7.0
             ChefAPI::Connection |      X-Chef-Version: 11.4.0
             ChefAPI::Connection | ===> Detected multipart body
             ChefAPI::Connection |      Content-Type: multipart/form-data; boundary=------ChefAPIMultipartBoundary
             ChefAPI::Connection |      Content-Length: 1377
             ChefAPI::Connection | ===> Adding signed header authentication...
         ChefAPI::Authentication | ===> Parsing private key...
         ChefAPI::Authentication |      Detected private key is the path to a file
             ChefAPI::Connection |      X-Ops-Sign: algorithm=sha1;version=1.0;
             ChefAPI::Connection |      X-Ops-Userid: hendrenj
             ChefAPI::Connection |      X-Ops-Timestamp: 2017-07-07T23:01:12Z
             ChefAPI::Connection |      X-Ops-Content-Hash: 6/H6D4hfy8wcNLjVEZI/ObW04y0=
             ChefAPI::Connection |      X-Ops-Authorization-1: nZ5QITdDMh8ddr9O++A85Z7SF//JKe4ynkCVSJjt77OuBRiktaobR+IlqGHa
             ChefAPI::Connection |      X-Ops-Authorization-2: 7bNT0cvzjnlr93daK2fK+TncE4iQ6gL3cueGNVpgXwqek2T83ga/MttyIskG
             ChefAPI::Connection |      X-Ops-Authorization-3: RAx3fHWPjcbASxBFTONbT14ZLBYuw/ipQfnLEnWzYub8PhP+91PBnWz39zQW
             ChefAPI::Connection |      X-Ops-Authorization-4: kNzVdnYlRCL1PhClNP/hGHhueQZE/YKxlzqIfQAZHYCyy1Geym5Baou6usGN
             ChefAPI::Connection |      X-Ops-Authorization-5: I9hNPkU4GN42USAG1h4VL12dxTemab8xclGFcqBTWS8BePtJdW6OWBIMwW8Q
             ChefAPI::Connection |      X-Ops-Authorization-6: CIpcJdd+957ZRJ0SiPFjMrFXyPRLEzHY8/VEGovmjA==
             ChefAPI::Connection | **** Disabling SSL verification...
             ChefAPI::Connection | **** Neither ChefAPI nor the maintainers are responsible for damages incurred as a result of disabling SSL verification. Please use this with extreme caution, or consider specifying a custom certificate using `config.ssl_pem_file'.
             ChefAPI::Connection |      Raw response:
             ChefAPI::Connection |      500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
             ChefAPI::Connection | ===> Parsing response as error...
             ChefAPI::Connection |      Detected response as text/plain
                      Stove::Cli | >>>> Stove experienced an error!
                      Stove::Cli | >>>> ChefAPI::Error::HTTPServerUnavailable
                      Stove::Cli | >>>> The Chef Server is currently unavailable or is not currently accepting client connections. Please ensure the server is accessible via ping or telnet on your local network. If this error persists, please contact your network administrator.

                      Stove::Cli | >>>> /home/jay/.chefdk/gem/ruby/2.3.0/gems/chef-api-0.7.0/lib/chef-api/connection.rb:439:in `error'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/chef-api-0.7.0/lib/chef-api/connection.rb:296:in `block in request'
/opt/chefdk/embedded/lib/ruby/2.3.0/net/http.rb:853:in `start'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/chef-api-0.7.0/lib/chef-api/connection.rb:282:in `request'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/chef-api-0.7.0/lib/chef-api/connection.rb:124:in `post'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/community.rb:54:in `upload'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/mixins/instanceable.rb:20:in `method_missing'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/plugins/community.rb:15:in `block in <class:Community>'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/plugins/base.rb:12:in `instance_eval'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/plugins/base.rb:12:in `block in run'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/plugins/base.rb:44:in `block in run_actions'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/plugins/base.rb:43:in `each'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/plugins/base.rb:43:in `run_actions'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/plugins/base.rb:33:in `run'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/runner.rb:30:in `run_plugin'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/runner.rb:18:in `run'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/lib/stove/cli.rb:75:in `execute!'
/home/jay/.chefdk/gem/ruby/2.3.0/gems/stove-5.2.0/bin/stove:4:in `<top (required)>'
/home/jay/.chefdk/gem/ruby/2.3.0/bin/stove:22:in `load'
/home/jay/.chefdk/gem/ruby/2.3.0/bin/stove:22:in `<main>'
```

The 500 error appears to be coming from Rails (`/var/log/supermarket/rails/current`) on the Supermarket server:

```
2017-07-07_23:01:32.83729 F, [2017-07-07T17:01:32.837186 #13830] FATAL -- : [992902df-45b8-4dc8-8cd2-7bfd906f2339]   
2017-07-07_23:01:32.83731 F, [2017-07-07T17:01:32.837254 #13830] FATAL -- : [992902df-45b8-4dc8-8cd2-7bfd906f2339] ActionController::RoutingError (No route matches [POST] "/cookbooks"):
2017-07-07_23:01:32.83731 F, [2017-07-07T17:01:32.837285 #13830] FATAL -- : [992902df-45b8-4dc8-8cd2-7bfd906f2339]   
2017-07-07_23:01:32.83839 F, [2017-07-07T17:01:32.837328 #13830] FATAL -- : [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
2017-07-07_23:01:32.83841 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2017-07-07_23:01:32.83843 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:36:in `call_app'
2017-07-07_23:01:32.83844 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:24:in `block in call'
2017-07-07_23:01:32.83844 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-07-07_23:01:32.83844 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-07-07_23:01:32.83844 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-07-07_23:01:32.83845 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:24:in `call'
2017-07-07_23:01:32.83845 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/request_id.rb:24:in `call'
2017-07-07_23:01:32.83845 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-07-07_23:01:32.83845 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-07-07_23:01:32.83845 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-07-07_23:01:32.83845 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
2017-07-07_23:01:32.83847 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/utf8-cleaner-0.2.5/lib/utf8-cleaner/middleware.rb:21:in `call'
2017-07-07_23:01:32.83847 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/engine.rb:522:in `call'
2017-07-07_23:01:32.83847 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:606:in `process_client'
2017-07-07_23:01:32.83866 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:702:in `worker_loop'
2017-07-07_23:01:32.83881 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
2017-07-07_23:01:32.83887 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:142:in `start'
2017-07-07_23:01:32.83892 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/bin/unicorn:126:in `<top (required)>'
2017-07-07_23:01:32.83896 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
2017-07-07_23:01:32.83898 [992902df-45b8-4dc8-8cd2-7bfd906f2339] vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'
2017-07-07_23:01:32.83901 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/cli/exec.rb:74:in `load'
2017-07-07_23:01:32.83904 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/cli/exec.rb:74:in `kernel_load'
2017-07-07_23:01:32.83907 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/cli/exec.rb:27:in `run'
2017-07-07_23:01:32.83910 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/cli.rb:360:in `exec'
2017-07-07_23:01:32.83917 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2017-07-07_23:01:32.83934 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2017-07-07_23:01:32.83934 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
2017-07-07_23:01:32.83934 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/cli.rb:20:in `dispatch'
2017-07-07_23:01:32.83935 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
2017-07-07_23:01:32.83935 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/cli.rb:10:in `start'
2017-07-07_23:01:32.83937 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) exe/bundle:35:in `block in <top (required)>'
2017-07-07_23:01:32.83937 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
2017-07-07_23:01:32.83937 [992902df-45b8-4dc8-8cd2-7bfd906f2339] bundler (1.15.1) exe/bundle:27:in `<top (required)>'
2017-07-07_23:01:32.83938 [992902df-45b8-4dc8-8cd2-7bfd906f2339] /opt/supermarket/embedded/bin/bundle:23:in `load'
2017-07-07_23:01:32.83938 [992902df-45b8-4dc8-8cd2-7bfd906f2339] /opt/supermarket/embedded/bin/bundle:23:in `<main>'
2017-07-07_23:01:32.83938 W, [2017-07-07T17:01:32.837968 #13830]  WARN -- : [992902df-45b8-4dc8-8cd2-7bfd906f2339] Can't verify CSRF token authenticity.
2017-07-07_23:01:32.83938 Error during failsafe response: ActionController::InvalidAuthenticityToken
2017-07-07_23:01:32.83938   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
2017-07-07_23:01:32.83938   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
2017-07-07_23:01:32.83939   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'
2017-07-07_23:01:32.83940   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:382:in `block in make_lambda'
2017-07-07_23:01:32.83944   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
2017-07-07_23:01:32.83944   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
2017-07-07_23:01:32.83945   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:170:in `block in halting'
2017-07-07_23:01:32.83962   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `block in call'
2017-07-07_23:01:32.83968   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `each'
2017-07-07_23:01:32.83971   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:454:in `call'
2017-07-07_23:01:32.83981   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
2017-07-07_23:01:32.83982   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
2017-07-07_23:01:32.83983   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/callbacks.rb:90:in `run_callbacks'
2017-07-07_23:01:32.83983   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
2017-07-07_23:01:32.83984   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal/rescue.rb:20:in `process_action'
2017-07-07_23:01:32.83986   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2017-07-07_23:01:32.83987   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `block in instrument'
2017-07-07_23:01:32.83988   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
2017-07-07_23:01:32.83988   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `instrument'
2017-07-07_23:01:32.83989   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2017-07-07_23:01:32.83989   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
2017-07-07_23:01:32.83990   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2017-07-07_23:01:32.83991   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/abstract_controller/base.rb:126:in `process'
2017-07-07_23:01:32.83991   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionview-5.0.3/lib/action_view/rendering.rb:30:in `process'
2017-07-07_23:01:32.83992   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal.rb:190:in `dispatch'
2017-07-07_23:01:32.83993   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_controller/metal.rb:251:in `block in action'
2017-07-07_23:01:32.83993   /opt/supermarket/embedded/service/supermarket/config/application.rb:56:in `block in <class:Application>'
2017-07-07_23:01:32.83994   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
2017-07-07_23:01:32.83994   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
2017-07-07_23:01:32.83995   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2017-07-07_23:01:32.83996   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:36:in `call_app'
2017-07-07_23:01:32.83996   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:24:in `block in call'
2017-07-07_23:01:32.83997   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-07-07_23:01:32.83997   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-07-07_23:01:32.83998   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-07-07_23:01:32.83999   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:24:in `call'
2017-07-07_23:01:32.83999   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/request_id.rb:24:in `call'
2017-07-07_23:01:32.84000   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-07-07_23:01:32.84000   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-07-07_23:01:32.84001   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-07-07_23:01:32.84002   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
2017-07-07_23:01:32.84002   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/utf8-cleaner-0.2.5/lib/utf8-cleaner/middleware.rb:21:in `call'
2017-07-07_23:01:32.84003   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/railties-5.0.3/lib/rails/engine.rb:522:in `call'
2017-07-07_23:01:32.84003   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:606:in `process_client'
2017-07-07_23:01:32.84004   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:702:in `worker_loop'
2017-07-07_23:01:32.84005   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
2017-07-07_23:01:32.84005   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:142:in `start'
2017-07-07_23:01:32.84006   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/gems/unicorn-5.3.0/bin/unicorn:126:in `<top (required)>'
2017-07-07_23:01:32.84006   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
2017-07-07_23:01:32.84007   /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'
2017-07-07_23:01:32.84007   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
2017-07-07_23:01:32.84008   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
2017-07-07_23:01:32.84009   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
2017-07-07_23:01:32.84009   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
2017-07-07_23:01:32.84010   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2017-07-07_23:01:32.84010   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2017-07-07_23:01:32.84011   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
2017-07-07_23:01:32.84011   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
2017-07-07_23:01:32.84012   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
2017-07-07_23:01:32.84012   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
2017-07-07_23:01:32.84013   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
2017-07-07_23:01:32.84014   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
2017-07-07_23:01:32.84014   /opt/supermarket/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
2017-07-07_23:01:32.84015   /opt/supermarket/embedded/bin/bundle:23:in `load'
2017-07-07_23:01:32.84015   /opt/supermarket/embedded/bin/bundle:23:in `<main>'
```
```
[vagrant@testkitchen-cub-rh7 ~]$ rpm -q supermarket
supermarket-3.1.14-1.el7.x86_64
```

**Comment by Poohblah** [comment]
Turns out I had the endpoint wrong in my stove command.  It should be `--endpoint https://testkitchen-cub-rh7.colorado.edu/api/v1`.
