### ISSUE TITLE
Install of supermarket can't associate app to user or create users

### ISSUE THREAD

**Issue by bashls** [chef/supermarket#1663]
With a new install of the supermarket application I can't click Create User:

```
The page you were looking for does not exist.

You may have mistyped the address or the page may have moved.
```

I found the following associated logs:

```
==> /var/log/supermarket/rails/current <==
2017-08-29_15:47:26.24987 F, [2017-08-29T15:47:26.249790 #18928] FATAL -- : [33d6186d-16c1-4814-a992-2c6511bf8cf2]
2017-08-29_15:47:26.24989 F, [2017-08-29T15:47:26.249870 #18928] FATAL -- : [33d6186d-16c1-4814-a992-2c6511bf8cf2] ActionController::RoutingError (No route matches [GET] "/signup"):
2017-08-29_15:47:26.25114 F, [2017-08-29T15:47:26.249899 #18928] FATAL -- : [33d6186d-16c1-4814-a992-2c6511bf8cf2]
2017-08-29_15:47:26.25115 F, [2017-08-29T15:47:26.249939 #18928] FATAL -- : [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
2017-08-29_15:47:26.25115 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2017-08-29_15:47:26.25115 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:36:in `call_app'
2017-08-29_15:47:26.25115 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:24:in `block in call'
2017-08-29_15:47:26.25116 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-08-29_15:47:26.25116 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-08-29_15:47:26.25116 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-08-29_15:47:26.25117 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/rack/logger.rb:24:in `call'
2017-08-29_15:47:26.25117 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/request_id.rb:24:in `call'
2017-08-29_15:47:26.25117 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-08-29_15:47:26.25117 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-08-29_15:47:26.25117 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-08-29_15:47:26.25117 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
2017-08-29_15:47:26.25118 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/utf8-cleaner-0.2.5/lib/utf8-cleaner/middleware.rb:21:in `call'
2017-08-29_15:47:26.25118 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/railties-5.0.3/lib/rails/engine.rb:522:in `call'
2017-08-29_15:47:26.25118 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:606:in `process_client'
2017-08-29_15:47:26.25118 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:702:in `worker_loop'
2017-08-29_15:47:26.25119 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
2017-08-29_15:47:26.25119 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:142:in `start'
2017-08-29_15:47:26.25119 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/bin/unicorn:126:in `<top (required)>'
2017-08-29_15:47:26.25119 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `load'
2017-08-29_15:47:26.25119 [33d6186d-16c1-4814-a992-2c6511bf8cf2] vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `<top (required)>'
2017-08-29_15:47:26.25119 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/cli/exec.rb:74:in `load'
2017-08-29_15:47:26.25121 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/cli/exec.rb:74:in `kernel_load'
2017-08-29_15:47:26.25121 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/cli/exec.rb:27:in `run'
2017-08-29_15:47:26.25121 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/cli.rb:365:in `exec'
2017-08-29_15:47:26.25121 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2017-08-29_15:47:26.25122 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2017-08-29_15:47:26.25122 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
2017-08-29_15:47:26.25122 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/cli.rb:22:in `dispatch'
2017-08-29_15:47:26.25122 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
2017-08-29_15:47:26.25122 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/cli.rb:13:in `start'
2017-08-29_15:47:26.25122 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) exe/bundle:30:in `block in <top (required)>'
2017-08-29_15:47:26.25123 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
2017-08-29_15:47:26.25123 [33d6186d-16c1-4814-a992-2c6511bf8cf2] bundler (1.15.3) exe/bundle:22:in `<top (required)>'
2017-08-29_15:47:26.25123 [33d6186d-16c1-4814-a992-2c6511bf8cf2] /opt/supermarket/embedded/bin/bundle:23:in `load'
2017-08-29_15:47:26.25123 [33d6186d-16c1-4814-a992-2c6511bf8cf2] /opt/supermarket/embedded/bin/bundle:23:in `<main>'

==> /var/log/supermarket/nginx/access.log <==
10.96.1.1 - - [2017-08-29T15:47:26+00:00]  "GET /signup?ref=community HTTP/1.1" 404 1098 "0.007" 2648 "https://chef-internal-mrkt/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
10.96.1.1 - - [2017-08-29T15:47:26+00:00]  "GET /assets/application-4aeb619eaed424802b451c88aea99edbe7949c21ea0f3aa54c48eafd4a99e303.css HTTP/1.1" 200 1062 "0.000" 34114 "https://chef-internal-mrkt/signup?ref=community" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
10.96.1.1 - - [2017-08-29T15:47:27+00:00]  "GET /assets/favicon-5f4080fbaa493463c163433fc3c7f57b891e43a00694557ac29c057cc7f62803.ico HTTP/1.1" 200 1122 "0.000" 1218 "https://chef-internal-mrkt/signup?ref=community" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
10.96.1.1 - - [2017-08-29T15:47:27+00:00]  "GET /assets/favicon-5f4080fbaa4934557ac29c057cc7f62803.ico HTTP/1.1" 200 1079 "0.000" 1218 "https://chef-internal-mrkt/signup?ref=community" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
```

If I click log in and login as one of my chef users, I am returned the following error:

```
An error has occurred
The redirect uri included is not valid.
```

**Comment by robbkidd** [comment]
```

**Comment by robbkidd** [comment]
@bashls Updated the comment above. Sorry about the misfire send!

**Comment by bashls** [comment]
Thanks for the quick response.

Modifying CHEF_SIGN_UP_URL from `/signup?ref=community` to `https://chef-internal-server/signup?ref=community` worked to resolve account creation, but I believe I confirmed there's no mismatch on the mrkt itself.  Its hostname is chef-internal-mrkt.

My etc/env has:

```
export FQDN="chef-internal-mrkt"
```

And on the chef server, in /etc/opscode/oc-id-applications/supermarket.json I have

```
"redirect_uri": "https://chef-internal-server/auth/chef_oauth2/callback"
```

Which I believe comes from `node.default['supermarket_omnibus']['chef_server_url']`?  I tried updating the redirect_uri there to chef-internal-mrkt and restarting the chef server, but there was no change to the error.

**Comment by robbkidd** [comment]
Yea. All these URLs are confusing.

On the Chef Server, `/etc/opscode/oc-id-applications/supermarket.json` should change like so:

```diff
- "redirect_uri": "https://chef-internal-server/auth/chef_oauth2/callback"
+ "redirect_uri": "https://chef-internal-mrkt/auth/chef_oauth2/callback"
```

That's telling the Chef Server's oauth2 provider to redirect freshly authenticated users _back_ to the Supermarket from which they came.

**Comment by bashls** [comment]
I noticed in the browser when I get the error, the URL in the address bar is as follows (sanitized a bit):

`https://chef-internal-server/id/oauth/authorize?client_id=deceb73b7625&redirect_uri=https%3A%2F%2Fchef-internal-mrkt%2Fauth%2Fchef_oauth2%2Fcallback&response_type=code&state=7db0`

If I substitute the `mrkt` in the redirect_uri there with `server` I am taken to a prompt to allow the app (although pressing the button fails.)

**Comment by bashls** [comment]
Do I need to do anything other than `chef-server-ctl restart` to pick up the change to supermarket.json?

**Comment by robbkidd** [comment]
@bashls A bit: `chef-server-ctl reconfigure && chef-server-ctl restart`

Reconfigure reads in the change and applies it to the auth service's database.

**Comment by robbkidd** [comment]
What are the errors you're seeing now in the browser and in the Supermarket logs you were viewing before?

**Comment by bashls** [comment]
Same error in the browser.  Logs:

```
==> /var/log/opscode/oc_id/current <==
2017-08-29_17:31:01.76811 I, [2017-08-29T17:31:01.768034 #10440]  INFO -- : Started POST "/id/auth/chef/callback" for 127.0.0.1 at 2017-08-29 17:31:01 +0000
2017-08-29_17:31:01.76872 I, [2017-08-29T17:31:01.768675 #10440]  INFO -- : (chef) Callback phase initiated.
2017-08-29_17:31:02.11519 W, [2017-08-29T17:31:02.115130 #10440]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /opt/opscode/embedded/service/gem/ruby/2.2.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
```

```
==> /var/log/opscode/oc_id/current <==
2017-08-29_17:31:02.13915 I, [2017-08-29T17:31:02.139089 #10440]  INFO -- : Redirected to https://chef-internal-server/id/oauth/authorize?client_id=deceb73b7625cd821c37d21784f459a&redirect_uri=https%3A%2F%2Fchef-internal-mrkt%2Fauth%2Fchef_oauth2%2Fcallback&response_type=code&state=9b7719f87af9d7fd5683d444bc11cb0
2017-08-29_17:31:02.13929 I, [2017-08-29T17:31:02.139250 #10440]  INFO -- : Completed 302 Found in 23ms (ActiveRecord: 0.0ms)
```

```
==> /var/log/opscode/nginx/access.log <==
10.96.199.84 - - [29/Aug/2017:17:31:02 +0000]  "POST /id/auth/chef/callback HTTP/1.1" 302 "0.372" 358 "https://chef-internal-server/id/signin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36" "127.0.0.1:9090" "302" "0.372" "-" "-" "-" "-" "-" 1649
```

```
2017-08-29_17:31:02.42252 I, [2017-08-29T17:31:02.420803 #10440]  INFO -- :   Parameters: {"client_id"=>"deceb73b7625b764821c37d21784f459a", "redirect_uri"=>"https://chef-internal-mrkt/auth/chef_oauth2/callback", "response_type"=>"code", "state"=>"9b771a9fd5683d444bc11cb0"}
```

```
2017-08-29_17:31:02.44652 I, [2017-08-29T17:31:02.444620 #10440]  INFO -- :   Rendered doorkeeper/authorizations/error.html.erb within layouts/application (0.1ms)
```

**Comment by bashls** [comment]
Fixed it, I was previously updating the redirect_uri in supermarket.json, I found it was still wrong in `/etc/opscode/chef-server.rb`, updating it there and doing another `chef-server-ctl reconfigure` resolved the issue.  Thanks for the excellent support!

**Comment by robbkidd** [comment]
A-ha! Yes, and I steered you wrong, too, by telling you to change `supermarket.json` and not the original `etc/opscode/chef-server.rb`. 🤦‍♂️  Sorry about that! Glad you're working now.
