### ISSUE TITLE
nodejs builds failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2018]
This is preventing us from shipping Supermarket:

```
      [Software: nodejs] I | 2021-07-05T21:19:41+00:00 | Building because `preparation' dirtied the cache

     [NetFetcher: nodejs] I | 2021-07-05T21:19:41+00:00 | Cleaning project directory `/var/cache/omnibus/supermarket/src/nodejs'

     [NetFetcher: nodejs] I | 2021-07-05T21:19:41+00:00 | Extracting `/var/cache/omnibus/supermarket/cache/node-v0.10.35.tar.gz' to `/var/cache/omnibus/supermarket/src/nodejs'

     [NetFetcher: nodejs] I | 2021-07-05T21:19:41+00:00 | $ gtar zxf /var/cache/omnibus/supermarket/cache/node-v0.10.35.tar.gz -C/var/cache/omnibus/supermarket/src/nodejs

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 | Starting build

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 | Cached builder checksum before build: 19e5ee058a4bf70fc51e15af836443acf28cc14b580c23829f7f9aef8fc7b8e0

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 | Environment:

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   CFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   CPPFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   CXXFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   LDFLAGS="-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   LD_RUN_PATH="/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   OMNIBUS_INSTALL_DIR="/opt/supermarket"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   PATH="/opt/supermarket/bin:/opt/supermarket/embedded/bin:/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin:/opt/omnibus-toolchain/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 |   PKG_CONFIG_PATH="/opt/supermarket/embedded/lib/pkgconfig"

        [Builder: nodejs] I | 2021-07-05T21:19:42+00:00 | $ /opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded

                          D | 2021-07-05T21:19:42+00:00 | Traceback (most recent call last):

                          D | 2021-07-05T21:19:42+00:00 |   File "./configure", line 681, in <module>

                          D | 2021-07-05T21:19:42+00:00 |     configure_node(output)

                          D | 2021-07-05T21:19:42+00:00 |   File "./configure", line 498, in configure_node

                          D | 2021-07-05T21:19:42+00:00 |     o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]

                          D | 2021-07-05T21:19:42+00:00 | IndexError: tuple index out of range

        [Builder: nodejs] W | 2021-07-05T21:19:42+00:00 | [1/5] Failed to execute command. Retrying in 10 seconds...

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 | Environment:

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   CFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   CPPFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   CXXFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   LDFLAGS="-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   LD_RUN_PATH="/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   OMNIBUS_INSTALL_DIR="/opt/supermarket"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   PATH="/opt/supermarket/bin:/opt/supermarket/embedded/bin:/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin:/opt/omnibus-toolchain/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 |   PKG_CONFIG_PATH="/opt/supermarket/embedded/lib/pkgconfig"

        [Builder: nodejs] I | 2021-07-05T21:19:52+00:00 | $ /opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded

                          D | 2021-07-05T21:19:52+00:00 | Traceback (most recent call last):

                          D | 2021-07-05T21:19:52+00:00 |   File "./configure", line 681, in <module>

                          D | 2021-07-05T21:19:52+00:00 |     configure_node(output)

                          D | 2021-07-05T21:19:52+00:00 |   File "./configure", line 498, in configure_node

                          D | 2021-07-05T21:19:52+00:00 |     o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]

                          D | 2021-07-05T21:19:52+00:00 | IndexError: tuple index out of range

        [Builder: nodejs] W | 2021-07-05T21:19:52+00:00 | [2/5] Failed to execute command. Retrying in 20 seconds...

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 | Environment:

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   CFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   CPPFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   CXXFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   LDFLAGS="-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   LD_RUN_PATH="/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   OMNIBUS_INSTALL_DIR="/opt/supermarket"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   PATH="/opt/supermarket/bin:/opt/supermarket/embedded/bin:/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin:/opt/omnibus-toolchain/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 |   PKG_CONFIG_PATH="/opt/supermarket/embedded/lib/pkgconfig"

        [Builder: nodejs] I | 2021-07-05T21:20:12+00:00 | $ /opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded

                          D | 2021-07-05T21:20:12+00:00 | Traceback (most recent call last):

                          D | 2021-07-05T21:20:12+00:00 |   File "./configure", line 681, in <module>

                          D | 2021-07-05T21:20:12+00:00 |     configure_node(output)

                          D | 2021-07-05T21:20:12+00:00 |   File "./configure", line 498, in configure_node

                          D | 2021-07-05T21:20:12+00:00 |     o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]

                          D | 2021-07-05T21:20:12+00:00 | IndexError: tuple index out of range

        [Builder: nodejs] W | 2021-07-05T21:20:12+00:00 | [3/5] Failed to execute command. Retrying in 40 seconds...

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 | Environment:

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   CFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   CPPFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   CXXFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   LDFLAGS="-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   LD_RUN_PATH="/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   OMNIBUS_INSTALL_DIR="/opt/supermarket"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   PATH="/opt/supermarket/bin:/opt/supermarket/embedded/bin:/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin:/opt/omnibus-toolchain/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 |   PKG_CONFIG_PATH="/opt/supermarket/embedded/lib/pkgconfig"

        [Builder: nodejs] I | 2021-07-05T21:20:52+00:00 | $ /opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded

                          D | 2021-07-05T21:20:52+00:00 | Traceback (most recent call last):

                          D | 2021-07-05T21:20:52+00:00 |   File "./configure", line 681, in <module>

                          D | 2021-07-05T21:20:52+00:00 |     configure_node(output)

                          D | 2021-07-05T21:20:52+00:00 |   File "./configure", line 498, in configure_node

                          D | 2021-07-05T21:20:52+00:00 |     o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]

                          D | 2021-07-05T21:20:52+00:00 | IndexError: tuple index out of range

        [Builder: nodejs] W | 2021-07-05T21:20:52+00:00 | [4/5] Failed to execute command. Retrying in 80 seconds...

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 | Environment:

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   CFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   CPPFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   CXXFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   LDFLAGS="-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   LD_RUN_PATH="/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   OMNIBUS_INSTALL_DIR="/opt/supermarket"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   PATH="/opt/supermarket/bin:/opt/supermarket/embedded/bin:/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin:/opt/omnibus-toolchain/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 |   PKG_CONFIG_PATH="/opt/supermarket/embedded/lib/pkgconfig"

        [Builder: nodejs] I | 2021-07-05T21:22:12+00:00 | $ /opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded

                          D | 2021-07-05T21:22:12+00:00 | Traceback (most recent call last):

                          D | 2021-07-05T21:22:12+00:00 |   File "./configure", line 681, in <module>

                          D | 2021-07-05T21:22:12+00:00 |     configure_node(output)

                          D | 2021-07-05T21:22:12+00:00 |   File "./configure", line 498, in configure_node

                          D | 2021-07-05T21:22:12+00:00 |     o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]

                          D | 2021-07-05T21:22:12+00:00 | IndexError: tuple index out of range

        [Builder: nodejs] W | 2021-07-05T21:22:12+00:00 | [5/5] Failed to execute command. Retrying in 160 seconds...

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 | Environment:

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   CFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   CPPFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   CXXFLAGS="-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   LDFLAGS="-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   LD_RUN_PATH="/opt/supermarket/embedded/lib"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   OMNIBUS_INSTALL_DIR="/opt/supermarket"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   PATH="/opt/supermarket/bin:/opt/supermarket/embedded/bin:/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin:/opt/omnibus-toolchain/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 |   PKG_CONFIG_PATH="/opt/supermarket/embedded/lib/pkgconfig"

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 | $ /opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded

                          D | 2021-07-05T21:24:52+00:00 | Traceback (most recent call last):

                          D | 2021-07-05T21:24:52+00:00 |   File "./configure", line 681, in <module>

                          D | 2021-07-05T21:24:52+00:00 |     configure_node(output)

                          D | 2021-07-05T21:24:52+00:00 |   File "./configure", line 498, in configure_node

                          D | 2021-07-05T21:24:52+00:00 |     o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]

                          D | 2021-07-05T21:24:52+00:00 | IndexError: tuple index out of range

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 | Execute: `/opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded': 310.6213s

        [Builder: nodejs] I | 2021-07-05T21:24:52+00:00 | Build nodejs: 310.6228s

[31mThe following shell command exited with status 1:



    $ CFLAGS=-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector CPPFLAGS=-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector CXXFLAGS=-I/opt/supermarket/embedded/include -O3 -D_FORTIFY_SOURCE=2 -fstack-protector LDFLAGS=-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib LD_RUN_PATH=/opt/supermarket/embedded/lib OMNIBUS_INSTALL_DIR=/opt/supermarket PATH=/opt/supermarket/bin:/opt/supermarket/embedded/bin:/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin:/opt/omnibus-toolchain/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin PKG_CONFIG_PATH=/opt/supermarket/embedded/lib/pkgconfig /opt/supermarket/embedded/bin/python ./configure --prefix=/opt/supermarket/embedded



Output:



    (nothing)



Error:



    Traceback (most recent call last):

  File "./configure", line 681, in <module>

    configure_node(output)

  File "./configure", line 498, in configure_node

    o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]

IndexError: tuple index out of range

[0m

[31m

/var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/util.rb:139:in `rescue in shellout!'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/util.rb:134:in `shellout!'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:876:in `shellout!'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:85:in `block in command'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:1066:in `instance_eval'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:1066:in `run'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:894:in `block (3 levels) in execute'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:916:in `with_retries'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:893:in `block (2 levels) in execute'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/instrumentation.rb:23:in `measure'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:892:in `block in execute'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:967:in `with_clean_env'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:891:in `execute'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:783:in `block (2 levels) in build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:782:in `each'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:782:in `block in build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/instrumentation.rb:23:in `measure'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/builder.rb:781:in `build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/software.rb:1224:in `execute_build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/software.rb:1102:in `build_me'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/project.rb:1078:in `block (2 levels) in build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/project.rb:1077:in `each'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/project.rb:1077:in `block in build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/licensing.rb:62:in `block in create_incrementally'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/licensing.rb:57:in `tap'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/licensing.rb:57:in `create_incrementally'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/project.rb:1076:in `build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/cli.rb:89:in `build'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/cli/base.rb:33:in `dispatch'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/lib/omnibus/cli.rb:42:in `execute!'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-5c1b453f577c/bin/omnibus:16:in `<top (required)>'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin/omnibus:23:in `load'

  /var/lib/buildkite-agent/builds/omnibus-ubuntu-1804-x86-64-prod-i-0684b02751f279038-1/chef/chef-supermarket-master-omnibus-release/omnibus/vendor/bundle/ruby/2.6.0/bin/omnibus:23:in `<top (required)>'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'

  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'

  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'

  /opt/omnibus-toolchain/bin/bundle:23:in `load'

  /opt/omnibus-toolchain/bin/bundle:23:in `<main>'[0m

[31mðŸš¨ Error: The command exited with status 1[0m
```

**Comment by tas50** [comment]
Potentially fixed by https://github.com/chef/omnibus-software/pull/1408

**Comment by tas50** [comment]
Resolved with https://github.com/chef/supermarket/pull/2020
