### ISSUE TITLE
supermarket site sharing is broken

### ISSUE THREAD

**Issue by lamont-granquist** [chef/supermarket#914]
i can't figure out how to create a new cookbook to share via either knife cookbook site share and/or knife supermarket share.
- supermarket site needs to completely ignore 'category' in uploads and not fail on invalid categories.  this seems to have been deprecated and the only way i found a valid category was to do a GET against a cookbook in the API and pull a valid one out of the API.  the categories have been hidden completely, but they're still absolutely mandatory to upload a new cookbook.
- knife-supermarket inherits from the knife cookbook site share command, which is different in v11 and v12 and all that code should be moved to the knife-supermarket gem -- the knife cookbook site share code should be removed and it should just fatal with a message to install and use the gem.
- the supermarket site share command needs to incorporate automatic metadata.json generation.
- even after hacking up knife cookbook site share code I can't figure out the necessary incantations to successfully upload a new cookbook.
- AAARGHHH, if i'm wasting hours on a Sunday with this, it must be terrible for our customers.

**Comment by burtlo** [comment]
This bad error message is still an issue if you do not include Categories.

```
✘ local  ~/test  knife cookbook site share burtlo-dependency -VV
INFO: Using configuration from /Users/franklinwebber/test/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to http://cookbooks.opscode.com/api/v1/cookbooks/burtlo-dependency
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: 117d2f8f-0296-41b4-9337-39873d949655
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 301 Moved Permanently
DEBUG: content-type: text/html
DEBUG: date: Fri, 21 Aug 2015 12:02:43 GMT
DEBUG: location: https://supermarket.chef.io/api/v1/cookbooks/burtlo-dependency
DEBUG: server: nginx/1.8.0
DEBUG: content-length: 184
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>

DEBUG: ---- End HTTP Response Body -----
DEBUG: Following redirect 1/10
DEBUG: Initiating GET to https://supermarket.chef.io/api/v1/cookbooks/burtlo-dependency
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: 117d2f8f-0296-41b4-9337-39873d949655
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 404 Not Found
DEBUG: cache-control: no-cache
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json; charset=utf-8
DEBUG: date: Fri, 21 Aug 2015 12:02:44 GMT
DEBUG: server: nginx/1.8.0
DEBUG: status: 404 Not Found
DEBUG: x-content-type-options: nosniff
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-request-id: 27d3c1b7-c820-4572-b559-2c0083abbabe
DEBUG: x-runtime: 0.005904
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-length: 87
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: �VJ-*�/��M-.NLO-V��V
J-�/-JNUH�O-V��/QH��,.�S�Ձ�N�OIU�R���w��sQ��?H
DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 404 Not Found:
FATAL: Unable to reach Opscode Cookbook Site: 404 "Not Found". Increase log verbosity (-VV) for more information.
DEBUG:
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chefdk/embedded/apps/chef/lib/chef/http.rb:145:in `request'
/opt/chefdk/embedded/apps/chef/lib/chef/rest.rb:119:in `get'
/opt/chefdk/embedded/apps/chef/lib/chef/knife/cookbook_site_share.rb:111:in `get_category'
/opt/chefdk/embedded/apps/chef/lib/chef/knife/cookbook_site_share.rb:62:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
/opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
/opt/chefdk/bin//knife:51:in `load'
/opt/chefdk/bin//knife:51:in `<main>'
```

**Comment by nathenharvey** [comment]
Both Supermarket and Knife should do a better job of displaying error message and/or enforcing required thing be included.

**Comment by lamont-granquist** [comment]
Pretty sure `knife cookbook site share` is still just busted and knife-supermarket and/or stove should be used instead.

We have an open item to merge knife-supermarket into core and make knife cookbook site share and alias to it (or vice versa, just make them the same).

**Comment by burtlo** [comment]
@lamont-granquist is there an public issue that could be referenced here in that issue. 

The reason I wanted to post my comments here is because when I googled for help I came here and I was thinking about me in the future or future people like me. :)

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/issues/3413
